# Generated by Django 4.1 on 2024-05-18 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('photo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='logo_company', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
